spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_prod?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root